#!/usr/bin/python3

import sys
import termcolor as tc
from argparse import ArgumentParser

from modules_elf import TitleManager

def main():
    parser = ArgumentParser(description="ElfTAI (Title/Alias/Items) - Program for organizing data with specific characteristics.", allow_abbrev=True)
    subp = parser.add_subparsers()
    
    list_parser = subp.add_parser('list', help='List information about one or all Titles')
    list_parser.add_argument('-e', '--entries', nargs='?', default=5, type=int, help='Number of latest items to print')
    list_parser.add_argument('name', nargs="*", help='Titles about which to print specific information. If none is given, print summary about all Titles.')
    list_parser.set_defaults(func=parse_list)

    find_parser = subp.add_parser('find', aliases=['search'], help='Display Titles that contain the given item')
    find_parser.add_argument('item', nargs=1, help='IDs to find')
    find_parser.set_defaults(func=parse_find)

    add_parser = subp.add_parser('add', help='Add a Title, alias or item')
    add_parser.add_argument('-t', '--title', type=str, help="Title to create or to which add the given alias/item")
    add_parser.add_argument('-a', '--alias', type=str, help="Alias to add to the given Title")
    add_parser.add_argument('-i', '--item', type=str, help="Item to add to the given Title")
    add_parser.set_defaults(func=parse_add)

    rm_parser = subp.add_parser('rm', help='Remove a Title, alias or item')
    rm_parser.add_argument('-t', '--title', type=str, help="Title to remove")
    rm_parser.add_argument('-a', '--alias', type=str, help="Alias to remove")
    rm_parser.add_argument('-i', '--item', type=str, help="Item to remove")
    rm_parser.set_defaults(func=parse_rm)

    comm_parser = subp.add_parser('comment', help='Change comment associated to a Title')
    comm_parser.add_argument('-t', '--title', type=str, help="Title of which to change comment")
    comm_parser.add_argument('string', nargs=1, type=str, help="Comment to associate to the Title")
    comm_parser.set_defaults(func=parse_comm)

    # TODO: operation 'name' for editing Title's title
    # TODO: operation 'comment' for editing/appending/adding comments

    args = parser.parse_args()
    tm = TitleManager('database.csv', 'backup_database.csv')
    try:
        args.func(args, tm)
    except:
        print("Wrong command line operation. Try running '{} -h'".format(sys.argv[0]))
    else:
        tm.close()

def parse_list(args, tm):
    if len(args.name) != 0:
        for name in args.name:
            if name != args.name[0]: print()
            try: tm.print_full(name.strip(), args.entries)
            except ValueError:
                print("Could not find Title by name/alias '{}'".format(name.strip()))
    else:
        tm.print_summary()

def parse_find(args, tm):
    tm.find_item(args.item[0])

def parse_add(args, tm):
    if not args.title:
        print("You need to specify a Title upon which to operate. Use the -t directive.")
        return

    if args.alias and args.item:
        print("For simplicity purposes, you cannot add alias and items together.\nUse 2 separate commands, please.")
        return

    if args.alias:
        try: tm.add_node(args.title, args.alias)
        except ValueError: #Node exists or alias already in node
            try: tm.add_alias(args.title, args.alias)
            except ValueError as ve: #Alias already in node
                print("Alias '{}' is already in some Title".format(args.alias, args.title))
            else:
                print("Added alias '{}' to Title identified by '{}'.".format(args.alias, args.title))
        else:
            print("Created Title '{}', with alias '{}'".format(args.title, args.alias))

    elif args.item:
        try: tm.add_node(args.title)
        except ValueError: #Node exists
            try: tm.add_item(args.title, args.item)
            except ValueError: #Item already in Node
                print("Item already exists in Title identified by '{}'".format(args.item, args.title))
            else:
                print("Added item '{}' to Title identified by '{}'".format(args.item, args.title))
        else:
            tm.add_item(args.title, args.item)
            print("Created Title '{}', with item '{}'".format(args.title, args.item))
    else:
        try: tm.add_node(args.title)
        except ValueError: #Node exists
            print("Title already exists! Nothing has been done.")
        else:
            print("Created Title '{}'".format(args.title))

def parse_rm(args, tm):
    if args.alias:
        if args.item:
            print("Ignoring the given item. Delete it on a separate execution, please.")
        if args.title:
            print("Title is not needed when deleting an alias, hence will be ignored.")

        try: tm.rm_alias(args.alias)
        except ValueError: #alias not found
            print("Could not remove alias '{}'. Confirm if it exists.".format(args.alias))
        else:
            print("Removed alias '{}'".format(args.alias))

    elif args.item:
        if not args.title:
            print("Items can only be removed from a single Title. Specify a Title with -t")
            return

        try: tm.rm_item(args.title, args.item)
        except ValueError as ve:
            print("Could not remove item '{}' from Title identified by '{}'.".format(args.item, args.title))
            print(ve)
        else:
            print("Removed item '{}' from Title identified by '{}'".format(args.item, args.title))

    elif args.title:
        inp = input(tc.colored("Confirm removal of Title identified by '{}' [Y/n]: ".format(args.title), "red", attrs=['bold']))
        if inp.lower().strip() == 'y':
            try: tm.rm_node(args.title)
            except ValueError:
                print("Title doesn't exist. Nothing has been done.")
            else:
                print("Removed")
        else:
            print("Canceled")

    else:
        print("Please, provide one of the following:\n1) A title with -t\n2) An alias with -a\n3) An item with -i and a title/alias with -t")

def parse_comm(args, tm):
    if not args.title:
        print("You must provide a title using argument directive -t")
        return
    
    try:
        retval = tm.set_comment(args.title, 0, args.string[0])
    except ValueError:
        print("Could not find Node identified by title '{}'".format(args.title))
    except IndexError:
        print("Comment of given index does not exist")
    else:
        print("Replaced old comment '{}'".format(retval))

if __name__=='__main__':
    main()
